export const AMENITIES_LIST = [
    "Swimming Pool",
    "Gym",
    "Parking",
    "Security",
    "Garden",
    "Elevator",
    "BBQ Area",
    "Children's Play Area",
    "Tennis Court",
    "Smart Home",
    "Storage",
    "Concierge",
    "Balcony",
    "Terrace",
    "Pet-Friendly",
    "Sea View",
    "City View",
    "Furnished",
    "Unfurnished",
    "Jacuzzi",
    "Sauna",
    "Steam Room",
    "Private Beach Access",
    "Community Pool", 
    "24/7 Security", 
    "Covered Parking", 
    "Visitor Parking", 
    "Wheelchair Accessible",
    "Fireplace", 
    "Home Theater",
  ];